Repository COS301-SE-2024/WorkWise-Central, pull requests merged in 2024-06, with the labels that each got.

#60 Refactor/user and company
  .github/workflows/lint.yml
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/create-company.dto.ts
  src/api-gateway/src/company/entities/company.entity.ts
  src/api-gateway/src/users/entities/user.entity.ts
Labels: Enhancement

#61 Enable cors
  src/api-gateway/src/main.ts
Labels: bug

#62 Adds name attribute to company
  src/api-gateway/src/company/entities/company.entity.ts
Labels: bug

#72 Updates README.md to add badges
  README.md
Labels: Documentation, Enhancement

#76 Integration sign up log in
  src/frontend/src/components/JoinCompanyModal.vue
  src/frontend/src/components/SplashScreen.vue
Labels: Enhancement, feature, frontend

#75 Adds check Username
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/users.controller.ts
  src/api-gateway/src/users/users.service.ts
Labels: backend

#78 fix: changed the export default to export default defineComponent
  src/frontend/src/components/SplashScreen.vue
Labels: bug

#80 fix: Resolved the errors regarding "cannot find type declaration"
  src/frontend/src/components/AddEmployee.vue
  src/frontend/src/components/ClientDetails.vue
  src/frontend/src/components/DashboardScreen.vue
  src/frontend/src/components/JobDetailsList.vue
  src/frontend/src/components/JobDetailsModal.vue
  src/frontend/src/components/JoinCompanyModal.vue
  src/frontend/src/components/RegisterCompanyModal.vue
  src/frontend/src/main.ts
  src/frontend/src/router/index.ts
  src/frontend/src/views/Modals.vue
  src/frontend/src/views/SplashView.vue
  src/frontend/tsconfig.app.json
  src/frontend/tsconfig.json
  src/frontend/tsconfig.node.json
  src/frontend/tsconfig.vitest.json
Labels: bug, Enhancement

#81 refactor: Added language trait to client.entity.ts
  src/api-gateway/src/client/dto/create-client.dto.ts
  src/api-gateway/src/client/entities/client.entity.ts
Labels: bug, backend

#82 refactor: Fixed language trait to client.entity.ts
  src/api-gateway/src/client/entities/client.entity.ts
Labels: bug

#84 feature/client-company-register
  src/frontend/src/components/AddEmployee.vue
  src/frontend/src/components/ClientDetails.vue
  src/frontend/src/components/RegisterCompanyModal.vue
Labels: bug, Enhancement

#87 fix: Create Job
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/job/dto/create-job.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.module.ts
  src/api-gateway/src/job/job.service.spec.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/users.controller.ts
Labels: bug, backend

#89 Integration sign up log in
  src/frontend/package.json
  src/frontend/src/components/SplashScreen.vue
Labels: bug, Enhancement

#92 Integration sign up log in
  src/frontend/src/components/SplashScreen.vue
Labels: bug, Enhancement, feature

#94 Integration sign up log in
  src/frontend/src/components/SplashScreen.vue
Labels: bug, Enhancement

#96 Fix/alert boxes register company
  src/frontend/src/components/SplashScreen.vue
Labels: bug, Enhancement

#98 fix: Update README.md
  README.md
Labels: Enhancement

#101 Sprint 1 components complete revision
  src/frontend/src/components/RegisterCompanyModal.vue
  src/frontend/src/components/SplashScreen.vue
Labels: bug

#118 Chore/dockerise application
  src/api-gateway/.dockerignore
  src/api-gateway/Dockerfile
  src/api-gateway/package.json
  src/api-gateway/src/auth/auth.service.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/docker-compose.yml
  src/frontend/.dockerignore
  src/frontend/Dockerfile
  src/frontend/nginx/default.conf
  src/frontend/tsconfig.node.json
  src/frontend/vite.config.ts
Labels: devops

#77 feat: Adds build.yml
  .github/workflows/build.yml
  .github/workflows/unit_test.yml
  README.md
  src/frontend/package.json
Labels: devops

#117 Feature/navigation bar
  src/frontend/package.json
  src/frontend/src/components/NavigationBar.vue
  src/frontend/src/router/index.ts
Labels: frontend

#119 refactor: made changes required to splashh and log in pages
  src/frontend/package.json
  src/frontend/src/components/SearchBar.vue
  src/frontend/src/components/SplashScreen.vue
  src/frontend/src/main.ts
  src/frontend/src/plugins/vuetify.ts
  src/frontend/src/router/index.ts
  src/frontend/tsconfig.json
Labels: frontend

#121 Feature/improving api responses
  src/api-gateway/package.json
  src/api-gateway/src/client/client.controller.ts
  src/api-gateway/src/client/client.service.ts
  src/api-gateway/src/client/dto/create-client.dto.ts
  src/api-gateway/src/client/entities/client.entity.ts
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/create-company.dto.ts
  src/api-gateway/src/job/dto/create-job.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/main.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/users.service.ts
Labels: Documentation, Enhancement, feature, backend

#126 Feature/search endpoints
  src/api-gateway/src/auth/dto/sign-in-dto.dto.ts
  src/api-gateway/src/client/client.controller.ts
  src/api-gateway/src/client/client.service.ts
  src/api-gateway/src/client/dto/create-client.dto.ts
  src/api-gateway/src/client/entities/client.entity.ts
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/create-company.dto.ts
  src/api-gateway/src/company/entities/company.entity.ts
  src/api-gateway/src/job/dto/create-job.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.controller.spec.ts
  src/api-gateway/src/job/job.module.ts
  src/api-gateway/src/job/job.service.spec.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
Labels: Documentation, Enhancement, feature, backend

#124 Feature/client management
  src/frontend/package.json
  src/frontend/src/components/ClientDesk.vue
  src/frontend/src/components/NavigationBar.vue
  src/frontend/src/components/ProfilePage.vue
  src/frontend/src/components/SearchBar.vue
  src/frontend/src/components/SplashScreen.vue
  src/frontend/src/router/index.ts
Labels: Enhancement, feature, frontend

#130 fix: improved docker-compose.yml
  src/docker-compose.yml
Labels: Enhancement

#132 Feature/client management
  src/frontend/package.json
  src/frontend/src/components/ClientDesk.vue
  src/frontend/src/components/DeleteClient.vue
  src/frontend/src/components/EditClient.vue
  src/frontend/src/components/NavigationBar.vue
  src/frontend/src/components/SearchBar.vue
  src/frontend/src/components/SplashScreen.vue
  src/frontend/src/store/store.ts
  src/frontend/tsconfig.json
Labels: Enhancement, feature, frontend

#139 Feature/client employee view
  src/frontend/src/components/ClientDesk.vue
  src/frontend/src/components/ClientDetails.vue
  src/frontend/src/components/ClientEmployeeView.vue
  src/frontend/src/components/EditClient.vue
Labels: Enhancement, feature

#142 Merge Refactor/employee
  src/api-gateway/src/employee/dto/create-employee.dto.ts
  src/api-gateway/src/employee/dto/read-employee.dto.ts
  src/api-gateway/src/employee/dto/update-employee.dto.ts
  src/api-gateway/src/employee/employee.service.ts
  src/api-gateway/src/employee/entities/employee.entity.ts
  src/api-gateway/src/role/dto/create-role.dto.ts
  src/api-gateway/src/role/dto/update-role.dto.ts
  src/api-gateway/src/role/entity/role.entity.ts
  src/api-gateway/src/role/role.controller.spec.ts
  src/api-gateway/src/role/role.controller.ts
  src/api-gateway/src/role/role.module.ts
  src/api-gateway/src/role/role.service.spec.ts
  src/api-gateway/src/role/role.service.ts
  src/api-gateway/src/team/dto/create-team.dto.ts
  src/api-gateway/src/team/dto/update-team.dto.ts
  src/api-gateway/src/team/entities/team.entity.ts
  src/api-gateway/src/team/team.controller.spec.ts
  src/api-gateway/src/team/team.controller.ts
  src/api-gateway/src/team/team.module.ts
  src/api-gateway/src/team/team.service.spec.ts
  src/api-gateway/src/team/team.service.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
Labels: feature, backend

#145 Revert "Merge Refactor/employee "
  src/api-gateway/src/employee/dto/create-employee.dto.ts
  src/api-gateway/src/employee/dto/read-employee.dto.ts
  src/api-gateway/src/employee/dto/update-employee.dto.ts
  src/api-gateway/src/employee/employee.service.ts
  src/api-gateway/src/employee/entities/employee.entity.ts
  src/api-gateway/src/role/dto/create-role.dto.ts
  src/api-gateway/src/role/dto/update-role.dto.ts
  src/api-gateway/src/role/entity/role.entity.ts
  src/api-gateway/src/role/role.controller.spec.ts
  src/api-gateway/src/role/role.controller.ts
  src/api-gateway/src/role/role.module.ts
  src/api-gateway/src/role/role.service.spec.ts
  src/api-gateway/src/role/role.service.ts
  src/api-gateway/src/team/dto/create-team.dto.ts
  src/api-gateway/src/team/dto/update-team.dto.ts
  src/api-gateway/src/team/entities/team.entity.ts
  src/api-gateway/src/team/team.controller.spec.ts
  src/api-gateway/src/team/team.controller.ts
  src/api-gateway/src/team/team.module.ts
  src/api-gateway/src/team/team.service.spec.ts
  src/api-gateway/src/team/team.service.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
Labels: bug

#146 Feature/client employee view
  src/frontend/src/components/ClientJobs.vue
  src/frontend/src/components/JobChecklist.vue
  src/frontend/src/components/JobLabels.vue
  src/frontend/src/components/TeamMemberList.vue
  src/frontend/src/views/TestView.vue
Labels: Enhancement, feature, frontend

#147 Feature/jobs backend
  src/api-gateway/src/email/email.service.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.module.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/users.service.ts
Labels: Enhancement, backend

#150 Add Job Card
  src/frontend/src/components/JobCard.vue
Labels: frontend

#151 Feature/user job client validation
  package.json
  src/api-gateway/src/auth/auth.service.ts
  src/api-gateway/src/auth/entities/validationResult.entity.ts
  src/api-gateway/src/client/client.controller.ts
  src/api-gateway/src/client/client.module.ts
  src/api-gateway/src/client/client.repository.ts
  src/api-gateway/src/client/client.service.ts
  src/api-gateway/src/client/dto/create-client.dto.ts
  src/api-gateway/src/client/entities/client.entity.ts
  src/api-gateway/src/client/tests/client.controller.spec.ts
  src/api-gateway/src/client/tests/client.service.spec.ts
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/company/company.module.ts
  src/api-gateway/src/company/company.repository.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/add-user-to-company.dto.ts
  src/api-gateway/src/company/dto/create-company.dto.ts
  src/api-gateway/src/company/dto/update-company.dto.ts
  src/api-gateway/src/company/entities/company.entity.ts
  src/api-gateway/src/company/tests/company.controller.spec.ts
  src/api-gateway/src/company/tests/company.service.spec.ts
  src/api-gateway/src/employee/employee.service.ts
  src/api-gateway/src/job/dto/create-job.dto.ts
  src/api-gateway/src/job/dto/update-job.dto.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.module.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/job/tests/job.controller.spec.ts
  src/api-gateway/src/job/tests/job.service.spec.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/tests/users.controller.spec.ts
  src/api-gateway/src/users/tests/users.service.spec.ts
  src/api-gateway/src/users/users.controller.ts
  src/api-gateway/src/users/users.module.ts
  src/api-gateway/src/users/users.repository.ts
  src/api-gateway/src/users/users.service.ts
Labels: Enhancement, feature, backend

#154 Chore/backend tests
  .github/workflows/unit_test.yml
  src/api-gateway/package.json
  src/api-gateway/src/auth/auth.module.ts
  src/api-gateway/src/client/dto/create-client.dto.ts
  src/api-gateway/src/client/entities/client.entity.ts
  src/api-gateway/src/job/dto/create-job.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/tests/job.controller.spec.ts
  src/api-gateway/src/job/tests/job.service.spec.ts
  src/api-gateway/src/notification/tests/notification.controller.spec.ts
  src/api-gateway/src/notification/tests/notification.gateway.spec.ts
  src/api-gateway/src/notification/tests/notification.service.spec.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/entities/user-confirmation.entity.ts
  src/api-gateway/src/users/tests/users.controller.spec.ts
  src/api-gateway/src/users/tests/users.service.spec.ts
  src/api-gateway/src/users/users.module.ts
  src/api-gateway/src/users/users.repository.ts
  src/api-gateway/src/users/users.service.ts
Labels: Enhancement, backend, devops

#157 Updates of navbar to allow support page
  src/frontend/src/components/AddClient.vue
  src/frontend/src/components/AddEmployee.vue
  src/frontend/src/components/AddJob.vue
  src/frontend/src/components/ManageEmployeesT.vue
  src/frontend/src/components/ManagerEditEmployee.vue
  src/frontend/src/components/NavigationBar.vue
  src/frontend/src/components/RegisterCompanyModal.vue
  src/frontend/src/components/Support.vue
  src/frontend/src/router/index.ts
  src/frontend/src/views/EmailConfirmation.vue
Labels: Enhancement, feature, frontend

#156 Feature/client employee view
  src/frontend/cypress.config.ts
  src/frontend/cypress/e2e/example.cy.ts
  src/frontend/img/WorkWiseLogo.png
  src/frontend/package.json
  src/frontend/src/components/AddClient.vue
  src/frontend/src/components/ClientDesk.cy.ts
  src/frontend/src/components/ClientDesk.vue
  src/frontend/src/components/ClientDetail.cy.ts
  src/frontend/src/components/DashboardScreen.cy.ts
  src/frontend/src/components/DashboardScreen.vue
  src/frontend/src/components/DeleteClient.vue
  src/frontend/src/components/EditClient.vue
  src/frontend/src/components/JobCard.cy.ts
  src/frontend/src/components/JobCard.vue
  src/frontend/src/components/JobChecklist.vue
  src/frontend/src/components/JobLabels.vue
  src/frontend/src/components/NavigationBar.vue
  src/frontend/src/components/SplashScreen.cy.ts
  src/frontend/src/components/SplashScreen.vue
  src/frontend/src/components/TeamMemberList.vue
  src/frontend/src/router/index.ts
  src/frontend/src/views/404Page.vue
  src/frontend/src/views/DashboardView.vue
Labels: Enhancement, feature, frontend

#164 Feature/client employee view
  src/frontend/src/components/ClientDesk.vue
  src/frontend/src/components/ClientDetail.cy.ts
  src/frontend/src/components/DashboardScreen.vue
  src/frontend/src/components/DeleteClient.vue
  src/frontend/src/components/EditClient.vue
  src/frontend/src/components/JobCard.vue
  src/frontend/src/components/JobLabels.vue
  src/frontend/src/components/SplashScreen.cy.ts
  src/frontend/src/components/SplashScreen.vue
Labels: Enhancement, feature, frontend

#160 Feature/client crud backend
  src/api-gateway/src/client/client.controller.ts
  src/api-gateway/src/client/client.module.ts
  src/api-gateway/src/client/client.repository.ts
  src/api-gateway/src/client/client.service.ts
  src/api-gateway/src/client/dto/create-client.dto.ts
  src/api-gateway/src/client/dto/update-client.dto.ts
  src/api-gateway/src/client/tests/client.service.spec.ts
  src/api-gateway/src/company/company.module.ts
  src/api-gateway/src/company/company.repository.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/job/tests/job.service.spec.ts
Labels: backend

#170 Hotfix/company exists
  src/api-gateway/src/client/client.controller.ts
  src/api-gateway/src/client/client.repository.ts
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/company/company.repository.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/employee.service.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/role/role.controller.ts
  src/api-gateway/src/team/team.controller.ts
  src/api-gateway/src/users/users.controller.ts
Labels: bug

#175 feat: added get all in company
  src/api-gateway/src/users/users.controller.ts
  src/api-gateway/src/users/users.repository.ts
Labels: bug

#177 Feature/job assignment view
  src/frontend/src/components/AddJob.vue
  src/frontend/src/components/JobAssignmentTable.vue
  src/frontend/src/components/JobCard.vue
  src/frontend/src/components/JobChecklist.vue
  src/frontend/src/components/JobLabels.vue
  src/frontend/src/components/TeamMemberList.vue
  src/frontend/src/router/index.ts
  src/frontend/src/views/TestView.vue
Labels: frontend

#180 bug: Routing Error Hotfix
  src/frontend/src/components/JobAssignmentTable.vue
  src/frontend/src/components/JobCard.vue
  src/frontend/src/router/index.ts
Labels: bug, frontend

#186 Feature/api documentation v2
  src/api-gateway/package.json
  src/api-gateway/src/auth/auth.service.ts
  src/api-gateway/src/client/client.controller.ts
  src/api-gateway/src/client/client.service.ts
  src/api-gateway/src/client/entities/client.entity.ts
  src/api-gateway/src/job/dto/create-job.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/main.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/tests/users.controller.spec.ts
  src/api-gateway/src/users/users.controller.ts
  src/api-gateway/src/users/users.repository.ts
  src/api-gateway/src/users/users.service.ts
Labels: Enhancement, backend
