Repository COS301-SE-2024/WorkWise-Central, pull requests merged in 2024-08, with the labels that each got.

#400 Feature/job assignment view2
  src/frontend/src/components/home/jobs/management/JobAssignmentTable.vue
  src/frontend/src/components/home/jobs/management/ManagerJobCard.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
Labels: frontend

#402 Feature/job improvement v2
  src/api-gateway/src/admin/admin.controller.ts
  src/api-gateway/src/admin/dto/request.dto.ts
  src/api-gateway/src/admin/entities/request-to-join.entity.ts
  src/api-gateway/src/client/client.repository.ts
  src/api-gateway/src/client/dto/create-client.dto.ts
  src/api-gateway/src/client/dto/update-client.dto.ts
  src/api-gateway/src/client/entities/client.entity.ts
  src/api-gateway/src/client/tests/client.controller.spec.ts
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/company/company.module.ts
  src/api-gateway/src/company/company.repository.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/create-company.dto.ts
  src/api-gateway/src/company/dto/update-company.dto.ts
  src/api-gateway/src/company/entities/company.entity.ts
  src/api-gateway/src/employee/entities/employee.entity.ts
  src/api-gateway/src/job/dto/create-job.dto.ts
  src/api-gateway/src/job/dto/create-tag.dto.ts
  src/api-gateway/src/job/dto/edit-tag.dto.ts
  src/api-gateway/src/job/dto/job-responses.dto.ts
  src/api-gateway/src/job/dto/update-job.dto.ts
  src/api-gateway/src/job/entities/job-status.entity.ts
  src/api-gateway/src/job/entities/job-tag.entity.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job-tag.repository.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.module.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/job/tests/job.controller.spec.ts
  src/api-gateway/src/role/role.module.ts
  src/api-gateway/src/team/team.module.ts
  src/api-gateway/src/users/entities/user-confirmation.entity.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/users.module.ts
  src/api-gateway/src/users/users.repository.ts
  src/api-gateway/src/utils/Utils.ts
Labels: Enhancement, backend

#403 Feature/job assignment view3
  src/frontend/src/components/home/jobs/management/AddComments.vue
  src/frontend/src/components/home/jobs/management/AttachImages.vue
  src/frontend/src/components/home/jobs/management/ChangeClientDialog.vue
  src/frontend/src/components/home/jobs/management/JobChecklist.vue
  src/frontend/src/components/home/jobs/management/JobNotes.vue
  src/frontend/src/components/home/jobs/management/LogInventory.vue
  src/frontend/src/components/home/jobs/management/ManagerJobCard.vue
  src/frontend/src/components/home/jobs/management/SelectMembers.vue
  src/frontend/src/components/home/jobs/management/UpdateDateDialog.vue
  src/frontend/src/components/home/jobs/management/UpdateJobStatus.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
Labels: bug, frontend

#404 Push of latest and updated changes to kanban and tutorial
  src/frontend/src/components/home/clients/management/AddClient.vue
  src/frontend/src/components/home/employees/management/AddEmployee.vue
  src/frontend/src/components/home/employees/management/EditEmployee.vue
  src/frontend/src/components/home/employees/management/ManageEmployees.vue
  src/frontend/src/components/home/jobs/KanbanV2/KanbanV2.vue
  src/frontend/src/components/home/jobs/management/BackLog.vue
  src/frontend/src/components/home/jobs/types.ts
  src/frontend/src/components/signup/RegisterCompanyModal.vue
  src/frontend/src/components/signup/__tests__/RegisterCompany.cy.ts
Labels: bug, feature, frontend

#406 updated kanban changes for edit kanban column
  src/frontend/src/components/home/jobs/KanbanV2/KanbanV2.vue
Labels: bug, feature, frontend

#408 Feature/client employee view
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/components/home/clients/management/ActionsMenu.vue
  src/frontend/src/components/home/clients/management/AddClient.vue
  src/frontend/src/components/home/clients/management/ClientDesk.vue
  src/frontend/src/components/home/clients/management/ClientDetails.vue
  src/frontend/src/components/home/clients/management/DeleteClient.vue
  src/frontend/src/components/home/clients/management/EditClient.vue
  src/frontend/src/components/home/employees/management/DeleteEmployee.vue
  src/frontend/src/components/home/employees/management/EditEmployee.vue
  src/frontend/src/components/home/employees/management/EmployeeDetails.vue
  src/frontend/src/components/home/employees/management/ManageEmployees.vue
  src/frontend/src/components/home/inventory/__tests__/AddInventory.cy.ts
  src/frontend/src/components/home/inventory/__tests__/DeleteInventory.cy.ts
  src/frontend/src/components/home/inventory/__tests__/EditInventory.cy.ts
  src/frontend/src/components/home/inventory/__tests__/InventoryDashboard.cy.ts
  src/frontend/src/components/home/inventory/__tests__/InventoryDetails.cy.ts
  src/frontend/src/components/home/inventory/management/DeleteInventory.vue
  src/frontend/src/components/home/inventory/management/EditInventory.vue
  src/frontend/src/components/home/inventory/management/InventoryDashboard.vue
  src/frontend/src/components/home/inventory/management/InventoryDetails.vue
  src/frontend/src/components/home/inventory/management/StockTakeManagement.vue
  src/frontend/src/components/home/inventory/reports/InventoryReports.vue
  src/frontend/src/components/home/jobs/task/ReportForm.vue
  src/frontend/src/components/home/jobs/task/TaskCenter.vue
  src/frontend/src/components/home/notifications/__tests__/MessageBoard.cy.ts
  src/frontend/src/components/home/notifications/__tests__/NotificationsPage.cy.ts
  src/frontend/src/components/home/notifications/appointments/AppointmentsPage.vue
  src/frontend/src/components/home/notifications/messages/MessageBoard.vue
  src/frontend/src/components/home/settings/SettingsMenu.vue
  src/frontend/src/components/home/settings/company/CompanySettings.vue
  src/frontend/src/components/home/settings/company/EditCompany.vue
  src/frontend/src/components/home/settings/company/EditRoles.vue
  src/frontend/src/components/home/settings/company/EditStructure.vue
  src/frontend/src/components/signup/SplashScreen.vue
  src/frontend/src/router/index.ts
  src/frontend/src/views/home/inventory/StockTakeManagementView.vue
  src/frontend/src/views/notfications/AppointmentsView.vue
  src/frontend/src/views/notfications/MessagesView.vue
Labels: Enhancement, feature, frontend

#409 feature/system-integration-sprint
  src/frontend/src/components/home/clients/management/AddClient.vue
  src/frontend/src/components/home/employees/management/AddEmployee.vue
  src/frontend/src/components/home/employees/management/EditEmployee.vue
  src/frontend/src/components/home/jobs/KanbanV2/KanbanV2.vue
  src/frontend/src/components/home/jobs/management/AddJob.vue
  src/frontend/src/components/home/jobs/types.ts
Labels: bug, Enhancement, feature, frontend

#411 Feature/join request system
  src/api-gateway/.eslintrc.js
  src/api-gateway/.prettierrc
  src/api-gateway/src/admin/admin.controller.ts
  src/api-gateway/src/admin/admin.module.ts
  src/api-gateway/src/admin/admin.repository.ts
  src/api-gateway/src/admin/admin.service.ts
  src/api-gateway/src/admin/dto/request.dto.ts
  src/api-gateway/src/admin/entities/invite-to-join.entity.ts
  src/api-gateway/src/admin/entities/request-to-join.entity.ts
  src/api-gateway/src/auth/auth.controller.ts
  src/api-gateway/src/client/dto/accept-request.dto.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/add-user-to-company.dto.ts
  src/api-gateway/src/email/email.service.ts
  src/api-gateway/src/email/templates/confirmation.hbs
  src/api-gateway/src/email/templates/inviteToCompany.hbs
  src/api-gateway/src/job/dto/create-tag.dto.ts
  src/api-gateway/src/job/dto/edit-tag.dto.ts
  src/api-gateway/src/job/dto/update-job.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job-tag.repository.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/job/tests/job.controller.spec.ts
  src/api-gateway/src/notification/dto/create-notification.dto.ts
  src/api-gateway/src/notification/entities/notification.entity.ts
  src/api-gateway/src/notification/notification.controller.ts
  src/api-gateway/src/notification/notification.service.ts
  src/api-gateway/src/notification/tests/notification.service.spec.ts
  src/api-gateway/src/users/dto/request-to-join.dto.ts
  src/api-gateway/src/utils/Custom Transformers/add-hashtag.transformer.ts
  src/api-gateway/src/utils/Custom Transformers/capitalise-words.transformer.ts
  src/api-gateway/src/utils/Utils.ts
Labels: Enhancement, backend

#418 Feature/job tasks
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/employee.repository.ts
  src/api-gateway/src/employee/employee.service.ts
  src/api-gateway/src/job/dto/assign-job.dto.ts
  src/api-gateway/src/job/dto/create-job.dto.ts
  src/api-gateway/src/job/dto/edit-tag.dto.ts
  src/api-gateway/src/job/dto/job-responses.dto.ts
  src/api-gateway/src/job/dto/update-job.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job-tag.repository.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
Labels: Enhancement, backend

#424 Feature/job tasks
  .gitignore
  src/api-gateway/package.json
  src/api-gateway/src/app.controller.ts
  src/api-gateway/src/app.module.ts
  src/api-gateway/src/app.service.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/create-company.dto.ts
  src/api-gateway/src/company/entities/company.entity.ts
  src/api-gateway/src/file/file.controller.ts
  src/api-gateway/src/file/file.service.ts
  src/api-gateway/src/job/dto/job-responses.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/shared/dtos/api-response.dto.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/tests/users.service.spec.ts
  src/api-gateway/src/users/users.controller.ts
  src/api-gateway/src/users/users.service.ts
  src/api-gateway/src/utils/Custom Validators/GetImageValidator.ts
Labels: bug, backend

#425 Refactor/role based access
  src/api-gateway/src/client/client.controller.ts
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/inventory/inventory.controller.ts
  src/api-gateway/src/role/dto/update-role.dto.ts
  src/api-gateway/src/shared/dtos/current-employee.dto.ts
Labels: backend

#427 fix: Populated fields in Job
  src/api-gateway/src/job/dto/update-job.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.repository.ts
Labels: bug, backend

#429 feature: updated changes to integration and frontend styling
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/components/home/clients/management/EditClient.vue
  src/frontend/src/components/home/employees/management/ManageEmployees.vue
  src/frontend/src/components/home/inventory/management/DeleteInventory.vue
  src/frontend/src/components/home/jobs/management/JobAssignmentTable.vue
  src/frontend/src/components/home/notifications/appointments/AppointmentsPage.vue
  src/frontend/src/components/home/notifications/management/NotificationsPage.vue
  src/frontend/src/components/home/settings/company/CompanyMain.vue
  src/frontend/src/components/home/settings/company/DeleteRole.vue
  src/frontend/src/components/home/settings/company/DeleteStatus.vue
  src/frontend/src/components/home/settings/company/EditCompany.vue
  src/frontend/src/components/home/settings/company/EditStatus.vue
  src/frontend/src/components/home/teams/management/CreateTeam.vue
Labels: feature, frontend

#433 Hotfix: update employee
  docs/.vuepress/.cache/deps/@vue_devtools-api.js
  docs/.vuepress/.cache/deps/@vue_devtools-api.js.map
  docs/.vuepress/.cache/deps/@vuepress_shared.js
  docs/.vuepress/.cache/deps/@vuepress_shared.js.map
  docs/.vuepress/.cache/deps/_metadata.json
  docs/.vuepress/.cache/deps/chunk-NRR3UUIY.js
  docs/.vuepress/.cache/deps/chunk-NRR3UUIY.js.map
  docs/.vuepress/.cache/deps/chunk-UKCZNIRO.js
  docs/.vuepress/.cache/deps/chunk-UKCZNIRO.js.map
  docs/.vuepress/.cache/deps/package.json
  docs/.vuepress/.cache/deps/vue-router.js
  docs/.vuepress/.cache/deps/vue-router.js.map
  docs/.vuepress/.cache/deps/vue.js
  docs/.vuepress/.cache/deps/vue.js.map
  docs/.vuepress/.temp/pages/demo3/architeturalDocs/architecturalDesignPattern.html.js
  docs/.vuepress/.temp/pages/demo3/architeturalDocs/constraints.html.js
  docs/.vuepress/.temp/pages/demo3/architeturalDocs/designStrategy.html.js
  docs/.vuepress/.temp/pages/demo3/architeturalDocs/index.html.js
  docs/.vuepress/.temp/pages/demo3/architeturalDocs/qualityRequirements.html.js
  docs/.vuepress/.temp/pages/demo3/architeturalDocs/styles.html.js
  docs/.vuepress/.temp/pages/demo3/architeturalDocs/techSpec.html.js
  docs/.vuepress/.temp/pages/demo3/businessDocs/classDiagrams.html.js
  docs/.vuepress/.temp/pages/demo3/businessDocs/functionalRequirements.html.js
  docs/.vuepress/.temp/pages/demo3/businessDocs/index.html.js
  docs/.vuepress/.temp/pages/demo3/businessDocs/marketResearch.html.js
  docs/.vuepress/.temp/pages/demo3/businessDocs/serviceContract.html.js
  docs/.vuepress/.temp/pages/demo3/businessDocs/usecaseDiagrams.html.js
  docs/.vuepress/.temp/pages/demo3/businessDocs/userCharacteristics.html.js
  docs/.vuepress/.temp/pages/demo3/businessDocs/userManual.html.js
  docs/.vuepress/.temp/pages/demo3/businessDocs/userStories.html.js
  docs/.vuepress/.temp/pages/demo3/databaseDocs/ERDiagrams.html.js
  docs/.vuepress/.temp/pages/demo3/databaseDocs/constraints.html.js
  docs/.vuepress/.temp/pages/demo3/databaseDocs/dataModel.html.js
  docs/.vuepress/.temp/pages/demo3/databaseDocs/dbFunctionalRequirements.html.js
  docs/.vuepress/.temp/pages/demo3/databaseDocs/dbNonFunctionalRequirements.html.js
  docs/.vuepress/.temp/pages/demo3/databaseDocs/dbSchema.html.js
  docs/.vuepress/.temp/pages/demo3/databaseDocs/index.html.js
  docs/.vuepress/.temp/pages/demo3/designDocs/index.html.js
  docs/.vuepress/.temp/pages/demo3/designDocs/styles.html.js
  docs/.vuepress/.temp/pages/demo3/designDocs/wireframes.html.js
  docs/.vuepress/.temp/pages/demo3/devOps/branching.html.js
  docs/.vuepress/.temp/pages/demo3/devOps/cicd.html.js
  docs/.vuepress/.temp/pages/demo3/devOps/codingStandards.html.js
  docs/.vuepress/.temp/pages/demo3/devOps/gitOrgMan.html.js
  docs/.vuepress/.temp/pages/demo3/devOps/index.html.js
  docs/.vuepress/.temp/pages/demo3/guide/index.html.js
  docs/.vuepress/.temp/pages/demo3/index.html.js
  docs/.vuepress/.temp/pages/index.html.js
  src/api-gateway/src/employee/dto/internal-update-employee.dto.ts
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/employee.repository.ts
  src/api-gateway/src/employee/employee.service.ts
Labels: backend

#435 hotfix: fixed issue with create default role
  src/api-gateway/src/role/role.service.ts
Labels: backend

#440 Kanban Updates fix to pull from database
  src/api-gateway/src/company/company.controller.ts
  src/frontend/cypress/e2e/example.cy.ts
  src/frontend/src/components/home/dashboard/types.ts
  src/frontend/src/components/home/employees/management/AddEmployee.vue
  src/frontend/src/components/home/employees/management/DeleteEmployee.vue
  src/frontend/src/components/home/employees/management/EditEmployee.vue
  src/frontend/src/components/home/employees/management/ManageEmployees.vue
  src/frontend/src/components/home/employees/types.ts
  src/frontend/src/components/home/jobs/KanbanV2/KanbanV2.vue
  src/frontend/src/components/home/jobs/types.ts
Labels: bug, feature, frontend

#439 Feature/job tasks
  src/api-gateway/src/admin/admin.service.ts
  src/api-gateway/src/admin/entities/request-to-join.entity.ts
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/company/company.repository.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/create-company.dto.ts
  src/api-gateway/src/company/dto/delete-employee-in-company.dto.ts
  src/api-gateway/src/employee/dto/create-employee.dto.ts
  src/api-gateway/src/job/entities/job-status.entity.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/job/tests/job.controller.spec.ts
  src/api-gateway/src/users/users.controller.ts
  src/api-gateway/src/users/users.service.ts
  src/api-gateway/src/utils/Custom Interceptors/body.interceptor.ts
  src/api-gateway/src/utils/Custom Validators/RegistrationNumber.ts
  src/docker-compose.yml
  src/frontend/package.json
  src/frontend/src/components/signup/JoinCompanyModal.vue
  src/frontend/src/components/signup/RegisterCompanyModal.vue
  src/frontend/src/components/signup/SplashScreen.vue
  src/frontend/src/components/signup/types.ts
  src/frontend/src/views/Modals.vue
Labels: backend

#443 Latest changes to AddJob
  src/frontend/cypress/e2e/example.cy.ts
  src/frontend/cypress/support/index.ts
  src/frontend/package.json
  src/frontend/src/components/home/jobs/KanbanV2/KanbanV2.vue
  src/frontend/src/components/home/jobs/management/AddJob.vue
  src/frontend/src/components/home/jobs/types.ts
Labels: bug, Enhancement, feature, frontend

#445 feature/job-attachments
  src/api-gateway/src/job/dto/create-job.dto.ts
  src/api-gateway/src/job/dto/job-responses.dto.ts
  src/api-gateway/src/job/dto/update-job.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/users/users.controller.ts
Labels: backend

#446 hotfix/employee: issue with creating an owner sorted out
  src/api-gateway/src/employee/employee.service.ts
Labels: backend

#448 Updates to the request
  src/frontend/src/components/home/clients/management/AddClient.vue
  src/frontend/src/components/home/employees/management/DeleteEmployee.vue
  src/frontend/src/components/home/employees/management/ManageEmployees.vue
  src/frontend/src/components/home/help/tutorial/Tutorial.vue
Labels: bug, frontend

#450 Hotfix/employee: fixed issue with create employee
  src/api-gateway/src/employee/entities/employee.entity.ts
Labels: backend

#451 Hotfix: invntory fixed
  src/api-gateway/src/inventory/inventory.controller.ts
  src/api-gateway/src/inventory/inventory.repository.ts
  src/api-gateway/src/inventory/inventory.service.ts
  src/frontend/src/components/home/inventory/management/InventoryDashboard.vue
Labels: backend

#447 Feature/job history
  src/api-gateway/src/job/dto/assign-job.dto.ts
  src/api-gateway/src/job/dto/update-job.dto.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/users/users.service.ts
Labels: backend

#453 feature/docs-edit: issue with detailed all fixed
  src/api-gateway/src/employee/employee.repository.ts
  src/api-gateway/src/employee/employee.service.ts
Labels: backend

#454 chore: updated scripts
  package.json
Labels: backend

#508 Feature/job assignment view3
  src/frontend/src/components/home/jobs/management/AddComments.vue
  src/frontend/src/components/home/jobs/management/CheckOffItems.vue
  src/frontend/src/components/home/jobs/management/GetJobImages.vue
  src/frontend/src/components/home/jobs/management/JobAssignmentTable.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
  src/frontend/src/components/home/settings/company/ManageCompanies.vue
  src/frontend/src/components/home/settings/user/UserPage.vue
Labels: bug, frontend

#510 Refactor frontend
  src/frontend/index.html
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/components/home/clients/management/AddClient.vue
  src/frontend/src/components/home/clients/management/ClientDesk.vue
  src/frontend/src/components/home/clients/management/ClientDetails.vue
  src/frontend/src/components/home/clients/management/DeleteClient.vue
  src/frontend/src/components/home/clients/management/EditClient.vue
  src/frontend/src/components/home/employees/management/AddEmployee.vue
  src/frontend/src/components/home/employees/management/DeleteEmployee.vue
  src/frontend/src/components/home/employees/management/EditEmployee.vue
  src/frontend/src/components/home/employees/management/EmployeeDetails.vue
  src/frontend/src/components/home/employees/management/ManageEmployees.vue
  src/frontend/src/components/home/inventory/management/AddInventory.vue
  src/frontend/src/components/home/inventory/management/DeleteInventory.vue
  src/frontend/src/components/home/inventory/management/EditInventory.vue
  src/frontend/src/components/home/inventory/management/InventoryDashboard.vue
  src/frontend/src/components/home/inventory/management/InventoryDetails.vue
  src/frontend/src/components/home/inventory/management/StockTakeManagement.vue
  src/frontend/src/components/home/inventory/reports/GenerateReport.vue
  src/frontend/src/components/home/inventory/reports/InventoryReports.vue
  src/frontend/src/components/home/inventory/reports/LogStockMovement.vue
  src/frontend/src/components/home/jobs/management/AddComments.vue
  src/frontend/src/components/home/jobs/management/AddJob.vue
  src/frontend/src/components/home/jobs/management/CheckOffItems.vue
  src/frontend/src/components/home/jobs/management/GetJobImages.vue
  src/frontend/src/components/home/jobs/management/JobAssignmentTable.vue
  src/frontend/src/components/home/jobs/management/ManagerJobCard.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
  src/frontend/src/components/home/notifications/appointments/AppointmentsPage.vue
  src/frontend/src/components/home/settings/company/CompanyMain.vue
  src/frontend/src/components/home/settings/company/CompanySettings.vue
  src/frontend/src/components/home/settings/company/CreatePriority.vue
  src/frontend/src/components/home/settings/company/CreateRoles.vue
  src/frontend/src/components/home/settings/company/CreateStatus.vue
  src/frontend/src/components/home/settings/company/CreateTags.vue
  src/frontend/src/components/home/settings/company/DeletePriority.vue
  src/frontend/src/components/home/settings/company/DeleteRole.vue
  src/frontend/src/components/home/settings/company/DeleteStatus.vue
  src/frontend/src/components/home/settings/company/DeleteTags.vue
  src/frontend/src/components/home/settings/company/EditCompany.vue
  src/frontend/src/components/home/settings/company/EditPriority.vue
  src/frontend/src/components/home/settings/company/EditRoles.vue
  src/frontend/src/components/home/settings/company/EditStatus.vue
  src/frontend/src/components/home/settings/company/EditStructure.vue
  src/frontend/src/components/home/settings/company/EditTags.vue
  src/frontend/src/components/home/settings/company/ManageCompanies.vue
  src/frontend/src/components/home/teams/management/CreateTeam.vue
  src/frontend/src/components/home/teams/management/DeleteTeam.vue
  src/frontend/src/components/home/teams/management/TeamsDashboard.vue
  src/frontend/src/components/home/teams/management/UpdateTeam.vue
  src/frontend/src/components/signup/CreateNewPassword.vue
  src/frontend/src/components/signup/JoinCompanyModal.vue
  src/frontend/src/components/signup/RegisterCompanyModal.vue
  src/frontend/src/components/signup/SplashScreen.vue
  src/frontend/src/plugins/vuetify.ts
  src/frontend/src/router/index.ts
  src/frontend/src/shims-vue.d.ts
  src/frontend/src/views/signup/NewPasswordView.vue
Labels: Enhancement, feature, frontend

#512 Feature/structure view backend
  src/api-gateway/package.json
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/employee.repository.ts
  src/api-gateway/src/employee/employee.service.ts
  src/frontend/src/components/home/settings/company/CompanySettings.vue
  src/frontend/src/components/home/settings/company/EditStructure.vue
Labels: backend

#513 refactor: issue with get role for company fixed
  src/api-gateway/src/role/role.repository.ts
  src/api-gateway/src/role/role.service.ts
Labels: backend

#511 Fix addjob Kanban and EditEmployee
  src/frontend/src/components/home/clients/management/AddClient.vue
  src/frontend/src/components/home/clients/management/ClientDesk.vue
  src/frontend/src/components/home/dashboard/home/Calendar.vue
  src/frontend/src/components/home/dashboard/home/DashboardScreen.vue
  src/frontend/src/components/home/employees/management/AddEmployee.vue
  src/frontend/src/components/home/employees/management/EditEmployee.vue
  src/frontend/src/components/home/employees/management/ManageEmployees.vue
  src/frontend/src/components/home/jobs/KanbanV2/Archive.vue
  src/frontend/src/components/home/jobs/KanbanV2/KanbanV2.vue
  src/frontend/src/components/home/jobs/management/AddJob.vue
  src/frontend/src/components/home/jobs/types.ts
  src/frontend/src/components/signup/RegisterCompanyModal.vue
Labels: Enhancement, feature, frontend

#523 fix to register company and rolebased access to ui
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/components/home/employees/management/AddEmployee.vue
  src/frontend/src/components/home/employees/management/ManageEmployees.vue
  src/frontend/src/components/home/help/tutorial/Tutorial.vue
  src/frontend/src/components/signup/RegisterCompanyModal.vue
Labels: feature, frontend

#534 Refactor/backend docs
  src/api-gateway/src/employee/dto/update-employee.dto.ts
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/entities/employee.entity.ts
  src/api-gateway/src/inventory/entities/inventory.entity.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/role/dto/create-role.dto.ts
  src/api-gateway/src/role/dto/update-role.dto.ts
  src/api-gateway/src/role/role.controller.ts
  src/api-gateway/src/role/role.service.ts
  src/api-gateway/src/team/team.controller.ts
  src/api-gateway/src/team/tests/team.service.spec.ts
  src/api-gateway/src/users/entities/user.entity.ts
Labels: backend

#536 Feature/job assignment view3
  src/frontend/src/components/home/jobs/management/AddComments.vue
  src/frontend/src/components/home/jobs/management/ChangeClientDialog.vue
  src/frontend/src/components/home/jobs/management/CheckOffItems.vue
  src/frontend/src/components/home/jobs/management/EditDetailsJobCard.vue
  src/frontend/src/components/home/jobs/management/GetJobImages.vue
  src/frontend/src/components/home/jobs/management/JobAssignmentTable.vue
  src/frontend/src/components/home/jobs/management/JobHistory.vue
  src/frontend/src/components/home/jobs/management/JobTags.vue
  src/frontend/src/components/home/jobs/management/ManagerJobCard.vue
  src/frontend/src/components/home/jobs/management/SelectMembers.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
  src/frontend/src/components/home/settings/company/ManageCompanies.vue
Labels: frontend

#535 support page with descriptions
  src/frontend/src/components/home/help/tutorial/Tutorial.vue
Labels: bug, Documentation, feature, frontend

#562 Feature/stock take
  src/api-gateway/src/app.module.ts
  src/api-gateway/src/inventory/dto/update-inventory.dto.ts
  src/api-gateway/src/inventory/inventory.controller.ts
  src/api-gateway/src/inventory/inventory.service.ts
  src/api-gateway/src/role/role.service.ts
  src/api-gateway/src/stocktake/dto/create-stocktake.dto.ts
  src/api-gateway/src/stocktake/dto/update-stocktake.dto.ts
  src/api-gateway/src/stocktake/entities/stocktake.entity.ts
  src/api-gateway/src/stocktake/stocktake.controller.ts
  src/api-gateway/src/stocktake/stocktake.module.ts
  src/api-gateway/src/stocktake/stocktake.repository.ts
  src/api-gateway/src/stocktake/stocktake.service.ts
Labels: backend

#564 Feature/correcting user
  src/api-gateway/src/admin/admin.controller.ts
  src/api-gateway/src/client/client.controller.ts
  src/api-gateway/src/client/client.repository.ts
  src/api-gateway/src/client/client.service.ts
  src/api-gateway/src/client/dto/update-client.dto.ts
  src/api-gateway/src/client/tests/client.controller.spec.ts
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/company/company.repository.ts
  src/api-gateway/src/company/dto/create-company.dto.ts
  src/api-gateway/src/company/dto/update-company.dto.ts
  src/api-gateway/src/company/tests/company.controller.spec.ts
  src/api-gateway/src/inventory/dto/update-inventory.dto.ts
  src/api-gateway/src/job/dto/create-job.dto.ts
  src/api-gateway/src/job/dto/create-tag.dto.ts
  src/api-gateway/src/job/dto/edit-tag.dto.ts
  src/api-gateway/src/job/dto/job-attachment.dto.ts
  src/api-gateway/src/job/dto/job-comments.dto.ts
  src/api-gateway/src/job/dto/job-status.dto.ts
  src/api-gateway/src/job/dto/job-tag.dto.ts
  src/api-gateway/src/job/dto/job-task-item.dto.ts
  src/api-gateway/src/job/dto/job-tasks.dto.ts
  src/api-gateway/src/job/dto/update-job.dto.ts
  src/api-gateway/src/job/entities/job-status.entity.ts
  src/api-gateway/src/job/entities/job-tag.entity.ts
  src/api-gateway/src/job/job-tag.repository.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/job/tests/job.controller.spec.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/users.controller.ts
  src/api-gateway/src/users/users.repository.ts
  src/api-gateway/src/users/users.service.ts
  src/frontend/src/components/signup/SplashScreen.vue
Labels: backend

#565 Bugfix/team
  src/api-gateway/src/team/dto/create-team.dto.ts
  src/api-gateway/src/team/dto/update-team.dto.ts
  src/api-gateway/src/team/entities/team.entity.ts
  src/api-gateway/src/team/team.controller.ts
  src/api-gateway/src/team/team.repository.ts
  src/api-gateway/src/team/team.service.ts
Labels: backend

#566 bugfix: issue with bulk role update fixed
  src/api-gateway/src/role/dto/update-role.dto.ts
  src/api-gateway/src/role/role.controller.ts
  src/api-gateway/src/role/role.service.ts
Labels: backend

#570 Hotfix: issue with delete employee fixed
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/employee.repository.ts
Labels: backend

#572 Feature/delete job
  src/api-gateway/src/admin/admin.module.ts
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/company/company.module.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/delete-employee-in-company.dto.ts
  src/api-gateway/src/email/email.service.ts
  src/api-gateway/src/email/templates/goodbye.hbs
  src/api-gateway/src/job/dto/assign-job.dto.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/notification/notification.module.ts
  src/api-gateway/src/users/users.module.ts
  src/api-gateway/src/users/users.service.ts
Labels: backend

#575 Feature/cascade delete employee
  src/api-gateway/src/employee/employee.repository.ts
  src/api-gateway/src/employee/employee.service.ts
  src/api-gateway/src/inventory/inventory.service.ts
  src/api-gateway/src/inventory/tests/inventory.service.spec.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/role/role.service.ts
  src/api-gateway/src/stocktake/entities/stocktake.entity.ts
  src/api-gateway/src/stocktake/stocktake.repository.ts
  src/api-gateway/src/stocktake/stocktake.service.ts
  src/api-gateway/src/team/team.repository.ts
  src/api-gateway/src/team/team.service.ts
  src/api-gateway/src/users/users.service.ts
Labels: backend

#573 Updates for issues
  src/frontend/cypress.config.ts
  src/frontend/cypress/support/component.ts
  src/frontend/package.json
  src/frontend/src/components/home/clients/management/AddClient.vue
  src/frontend/src/components/home/employees/management/DeleteEmployee.vue
  src/frontend/src/components/home/employees/management/EditEmployee.vue
  src/frontend/src/components/home/employees/management/ManageEmployees.vue
  src/frontend/src/components/home/help/tutorial/Tutorial.vue
  src/frontend/src/components/home/jobs/Kanban.vue
  src/frontend/src/components/home/jobs/KanbanV2/Archive.vue
  src/frontend/src/components/home/jobs/KanbanV2/KanbanV2.vue
  src/frontend/src/components/home/jobs/management/AddJob.vue
  src/frontend/src/components/signup/RegisterCompanyModal.vue
  src/frontend/src/components/signup/Tutorial.vue
  src/frontend/src/router/index.ts
  src/frontend/src/views/home/jobs/Archive.vue
Labels: bug, feature, frontend

#577 Feature/job assignment view4
  src/frontend/src/components/home/UserAvatar.vue
  src/frontend/src/components/home/jobs/management/CheckOffItems.vue
Labels: frontend, integration

#576 refactor/role: changed the edit and delete permission
  src/api-gateway/src/client/client.controller.ts
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/role/role.service.ts
  src/api-gateway/src/role/tests/role.service.spec.ts
  src/frontend/src/components/home/clients/management/ClientDesk.vue
  src/frontend/src/components/home/employees/management/ManageEmployees.vue
Labels: backend

#579 Feature/basic chat
  src/api-gateway/package.json
  src/api-gateway/src/app.module.ts
  src/api-gateway/src/chat/chat.controller.ts
  src/api-gateway/src/chat/chat.gateway.ts
  src/api-gateway/src/chat/chat.module.ts
  src/api-gateway/src/chat/chat.service.ts
  src/api-gateway/src/chat/dto/add-message.dto.ts
  src/api-gateway/src/chat/dto/create-chat.dto.ts
  src/api-gateway/src/chat/dto/get-chat-message.dto.ts
  src/api-gateway/src/chat/dto/update-chat-message.dto.ts
  src/api-gateway/src/chat/entities/chat-message.entity.ts
  src/api-gateway/src/chat/entities/chat.entity.ts
  src/api-gateway/src/chat/tests/chat.service.spec.ts
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/company/company.repository.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/delete-employee-in-company.dto.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/users/users.service.ts
  src/frontend/package.json
  src/frontend/src/router/index.ts
  src/frontend/src/views/UserChats.vue
Labels: backend

#587 hotfix: validate update role fixed
  src/api-gateway/src/role/role.service.ts
Labels: backend

#586 Forgot password integrated
  src/frontend/src/components/signup/CreateNewPassword.vue
  src/frontend/src/components/signup/SplashScreen.vue
Labels: integration

#610 Refactor/employee: List of potential subordinates and superiors added
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/employee.service.ts
Labels: backend

#612 Feature/job assignment view4
  src/api-gateway/src/client/client.service.ts
  src/frontend/src/components/home/jobs/management/ChangeClientDialog.vue
  src/frontend/src/components/home/jobs/management/CheckOffItems.vue
  src/frontend/src/components/home/jobs/management/EditDetailsJobCard.vue
  src/frontend/src/components/home/jobs/management/ManagerJobCard.vue
  src/frontend/src/components/home/settings/user/Notifications.vue
Labels: frontend

#614 Refactor/employee
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/employee/dto/create-employee.dto.ts
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/employee.repository.ts
  src/api-gateway/src/employee/employee.service.ts
Labels: backend

#620 hotfix: build issue on dev fixed
  package.json
  src/frontend/package.json
Labels: backend

#616 refactor: issue with role id fixed
  .github/workflows/build.yml
  src/api-gateway/src/employee/employee.repository.ts
  src/api-gateway/src/employee/employee.service.ts
  src/api-gateway/src/role/role.controller.ts
  src/api-gateway/src/role/role.service.ts
  src/api-gateway/tsconfig.json
  src/frontend/tsconfig.json
Labels: backend

#615 Feature/job assignment view4
  src/api-gateway/src/job/job.controller.ts
  src/frontend/dev-dist/registerSW.js
  src/frontend/src/components/home/jobs/management/AddComments.vue
  src/frontend/src/components/home/jobs/management/ChangeClientDialog.vue
  src/frontend/src/components/home/jobs/management/CheckOffItems.vue
  src/frontend/src/components/home/jobs/management/GetJobImages.vue
  src/frontend/src/components/home/jobs/management/JobAssignmentTable.vue
  src/frontend/src/components/home/jobs/management/JobHistory.vue
  src/frontend/src/components/home/jobs/management/JobStatus.vue
  src/frontend/src/components/home/jobs/management/JobTags.vue
  src/frontend/src/components/home/jobs/management/ManagerJobCard.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
  src/frontend/src/cypress.config.js
  src/frontend/src/cypress/fixtures/example.json
Labels: frontend
