Repository COS301-SE-2024/WorkWise-Central, pull requests merged in 2024-05, with the labels that each got.

#20 Develop
  src/api-gateway/.eslintrc.js
  src/api-gateway/.prettierrc
  src/api-gateway/package.json
  src/api-gateway/src/app.module.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/dto/update-user.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/users.controller.spec.ts
  src/api-gateway/src/users/users.controller.ts
  src/api-gateway/src/users/users.module.ts
  src/api-gateway/src/users/users.service.spec.ts
  src/api-gateway/src/users/users.service.ts
  src/api-gateway/test/stubs/user.stub.ts
Labels: feature

#25 Chore/adds test workflow
  .github/workflows/lint.yml
  .github/workflows/unit_test.yml
  README.md
  src/api-gateway/package.json
  src/api-gateway/src/users/dto/update-user.dto.ts
  src/api-gateway/src/users/users.service.spec.ts
  src/frontend/package.json
Labels: Enhancement

#36 Sign-in backend
  src/api-gateway/package.json
  src/api-gateway/src/app.module.ts
  src/api-gateway/src/auth/auth.controller.ts
  src/api-gateway/src/auth/auth.guard.ts
  src/api-gateway/src/auth/auth.module.ts
  src/api-gateway/src/auth/auth.service.ts
  src/api-gateway/src/auth/constants.ts
  src/api-gateway/src/auth/dto/sign-in-dto.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/users.controller.ts
  src/api-gateway/src/users/users.module.ts
  src/api-gateway/src/users/users.service.ts
Labels: feature, backend

#39 Feature/api swagger documentation
  src/api-gateway/nest-cli.json
  src/api-gateway/package.json
  src/api-gateway/src/auth/auth.controller.ts
  src/api-gateway/src/main.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/dto/update-user.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/users.controller.ts
  src/frontend/package.json
Labels: Documentation, backend

#41 Chore/error handling in backend
  src/api-gateway/src/auth/auth.controller.ts
  src/api-gateway/src/auth/auth.service.ts
  src/api-gateway/src/auth/dto/sign-in-response.dto.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/users.controller.spec.ts
  src/api-gateway/src/users/users.controller.ts
  src/api-gateway/src/users/users.service.spec.ts
  src/api-gateway/src/users/users.service.ts
  src/api-gateway/test/stubs/user.stub.ts
Labels: Enhancement, backend

#42 Refactor/updating user schema
  src/api-gateway/src/auth/auth.service.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/users.controller.spec.ts
  src/api-gateway/src/users/users.service.ts
  src/api-gateway/test/stubs/user.stub.ts
Labels: Enhancement

#54 Feature/sign up log in flow
  src/frontend/img/splash2.png
  src/frontend/src/App.vue
  src/frontend/src/components/AddEmployee.vue
  src/frontend/src/components/ClientDetails.vue
  src/frontend/src/components/JoinCompanyModal.vue
  src/frontend/src/components/RegisterCompanyModal.vue
  src/frontend/src/components/RegisterCompanyModal2.vue
  src/frontend/src/components/Splash.vue
  src/frontend/src/main.ts
  src/frontend/src/router/index.ts
Labels: feature, UserStory, frontend

#58 Feature/add user to company
  src/api-gateway/src/auth/auth.controller.ts
  src/api-gateway/src/auth/auth.module.ts
  src/api-gateway/src/auth/auth.service.ts
  src/api-gateway/src/auth/dto/sign-in-dto.dto.ts
  src/api-gateway/src/auth/dto/sign-in-response.dto.ts
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/company/company.module.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/add-user-to-company.dto.ts
  src/api-gateway/src/company/dto/create-company.dto.ts
  src/api-gateway/src/company/entities/company.entity.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/entities/user.entity.ts
  src/api-gateway/src/users/users.controller.ts
  src/api-gateway/src/users/users.module.ts
  src/api-gateway/src/users/users.service.ts
Labels: Enhancement, backend

#59 Fixed Type error in addUser
  src/api-gateway/src/company/company.service.ts
Labels: backend
