Repository COS301-SE-2024/WorkWise-Central, pull requests merged in 2024-09, with the labels that each got.

#625 Feature/job task conversion
  src/api-gateway/src/app.module.ts
  src/api-gateway/src/job/dto/convert-item-to-job.dto.ts
  src/api-gateway/src/job/dto/create-job.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/time-tracker/dto/create-time-tracker.dto.ts
  src/api-gateway/src/time-tracker/entities/time-tracker.entity.ts
  src/api-gateway/src/time-tracker/time-tracker.controller.ts
  src/api-gateway/src/time-tracker/time-tracker.module.ts
  src/api-gateway/src/time-tracker/time-tracker.repository.ts
  src/api-gateway/src/time-tracker/time-tracker.service.ts
Labels: backend

#624 Feature/job assignment view4
  src/frontend/package.json
  src/frontend/src/components/home/jobs/management/CheckOffItems.vue
  src/frontend/src/components/home/jobs/management/GenerateInvoice.vue
  src/frontend/src/components/home/jobs/management/LogJobInventory.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
  src/frontend/src/components/home/settings/company/ManageCompanies.vue
Labels: integration

#618 Refactor/jwt checks employee role team inventory
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/employee.service.ts
  src/api-gateway/src/inventory/inventory.controller.ts
  src/api-gateway/src/role/role.controller.ts
  src/api-gateway/src/stocktake/stocktake.controller.ts
  src/api-gateway/src/team/team.controller.ts
  src/api-gateway/src/team/tests/team.controller.spec.ts
Labels: backend

#628 Feature/hourly rate employee
  src/api-gateway/src/employee/dto/create-employee.dto.ts
  src/api-gateway/src/employee/dto/update-employee.dto.ts
  src/api-gateway/src/employee/employee.repository.ts
  src/api-gateway/src/employee/employee.service.ts
  src/api-gateway/src/employee/entities/employee.entity.ts
  src/api-gateway/src/role/dto/create-role.dto.ts
  src/api-gateway/src/role/dto/update-role.dto.ts
  src/api-gateway/src/role/entity/role.entity.ts
  src/api-gateway/src/role/role.service.ts
Labels: backend

#621 Refactor/frontend pt3
  src/frontend/index.html
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/components/home/clientcenter/ClientCenter.vue
  src/frontend/src/components/home/clients/client_portal/ReviewJob.vue
  src/frontend/src/components/home/clients/client_portal/ViewJobs.vue
  src/frontend/src/components/home/clients/management/AddClient.vue
  src/frontend/src/components/home/clients/management/ClientDesk.vue
  src/frontend/src/components/home/clients/management/DeleteClient.vue
  src/frontend/src/components/home/inventory/management/AddInventory.vue
  src/frontend/src/components/home/inventory/management/DeleteInventory.vue
  src/frontend/src/components/home/inventory/management/EditInventory.vue
  src/frontend/src/components/home/inventory/management/InventoryDashboard.vue
  src/frontend/src/components/home/inventory/management/StockTakeManagement.vue
  src/frontend/src/components/home/inventory/reports/InventoryReports.vue
  src/frontend/src/components/home/invoices/DeleteInvoice.vue
  src/frontend/src/components/home/invoices/EditInvoice.vue
  src/frontend/src/components/home/invoices/InvoiceCenter.vue
  src/frontend/src/components/home/invoices/InvoiceDashboard.vue
  src/frontend/src/components/home/invoices/ViewInvoices.vue
  src/frontend/src/components/home/settings/company/CompanyRequest.vue
  src/frontend/src/components/home/settings/company/CompanySettings.vue
  src/frontend/src/components/home/settings/company/CreatePriority.vue
  src/frontend/src/components/home/settings/company/CreateRoles.vue
  src/frontend/src/components/home/settings/company/CreateStatus.vue
  src/frontend/src/components/home/settings/company/CreateTags.vue
  src/frontend/src/components/home/settings/company/DeletePriority.vue
  src/frontend/src/components/home/settings/company/DeleteRole.vue
  src/frontend/src/components/home/settings/company/DeleteStatus.vue
  src/frontend/src/components/home/settings/company/DeleteTags.vue
  src/frontend/src/components/home/settings/company/EditCompany.vue
  src/frontend/src/components/home/settings/company/EditPriority.vue
  src/frontend/src/components/home/settings/company/EditRoles.vue
  src/frontend/src/components/home/settings/company/EditStatus.vue
  src/frontend/src/components/home/settings/company/EditTags.vue
  src/frontend/src/components/home/settings/company/HourlyRate.vue
  src/frontend/src/components/home/teams/management/CreateTeam.vue
  src/frontend/src/components/home/teams/management/TeamsDashboard.vue
  src/frontend/src/components/signup/SplashScreen.vue
  src/frontend/src/router/index.ts
  src/frontend/src/views/home/invoices/InvoiceCenter.vue
Labels: Enhancement, feature, frontend

#626 Updates Integration
  src/frontend/src/components/home/clients/management/AddClient.vue
  src/frontend/src/components/home/dashboard/home/Calendar.vue
  src/frontend/src/components/home/dashboard/types.ts
  src/frontend/src/components/home/employees/management/AddEmployee.vue
  src/frontend/src/components/home/employees/management/EditEmployee.vue
  src/frontend/src/components/home/help/support/Support.vue
  src/frontend/src/components/home/help/tutorial/Tutorial.vue
  src/frontend/src/components/home/jobs/KanbanV2/KanbanV2.vue
  src/frontend/src/components/home/jobs/management/AddJob.vue
  src/frontend/src/components/home/jobs/types.ts
  src/frontend/src/components/signup/RegisterCompanyModal.vue
Labels: bug, feature, frontend

#627 Feature/invoices
  src/api-gateway/src/client/client.service.ts
  src/api-gateway/src/inventory/dto/create-inventory.dto.ts
  src/api-gateway/src/inventory/dto/update-inventory.dto.ts
  src/api-gateway/src/inventory/entities/inventory.entity.ts
  src/api-gateway/src/invoices/dto/create-invoice.dto.ts
  src/api-gateway/src/invoices/dto/update-invoice.dto.ts
  src/api-gateway/src/invoices/entities/invoice.entity.ts
  src/api-gateway/src/invoices/invoice.controller.ts
  src/api-gateway/src/invoices/invoice.module.ts
  src/api-gateway/src/invoices/invoice.repository.ts
  src/api-gateway/src/invoices/invoice.service.ts
Labels: backend

#631 hotfix: 2 issues noticed from review session fixed
  src/frontend/src/components/home/clients/management/EditClient.vue
Labels: backend

#632 bugfix: issue with validation on rol, employee, team and stocktake fixed
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/role/role.controller.ts
  src/api-gateway/src/stocktake/stocktake.controller.ts
  src/api-gateway/src/team/team.controller.ts
Labels: backend

#645 Feature/client portal backend
  src/api-gateway/src/client/client.controller.ts
  src/api-gateway/src/client/client.service.ts
  src/api-gateway/src/client/dto/client-feedback.dto.ts
  src/api-gateway/src/client/dto/create-client.dto.ts
  src/api-gateway/src/client/dto/job-for-client.dto.ts
  src/api-gateway/src/client/dto/update-client.dto.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/create-company.dto.ts
  src/api-gateway/src/job/dto/update-job.dto.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/users/dto/create-user.dto.ts
  src/api-gateway/src/users/users.service.ts
  src/frontend/src/components/home/notifications/management/NotificationsPage.vue
Labels: bug, feature, backend

#650 Bugfix/employee
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/employee.service.ts
  src/api-gateway/src/employee/entities/employee.entity.ts
Labels: backend

#652 Feature/client portal backend
  src/api-gateway/src/company/company.repository.ts
  src/api-gateway/src/company/dto/create-company.dto.ts
  src/api-gateway/src/company/dto/update-company.dto.ts
  src/api-gateway/src/company/entities/company.entity.ts
  src/api-gateway/src/time-tracker/dto/create-time-tracker.dto.ts
  src/api-gateway/src/time-tracker/dto/time-spent.dto.ts
  src/api-gateway/src/time-tracker/dto/time-tracker-response.dto.ts
  src/api-gateway/src/time-tracker/time-tracker.controller.ts
  src/api-gateway/src/time-tracker/time-tracker.repository.ts
  src/api-gateway/src/time-tracker/time-tracker.service.ts
Labels: Enhancement, backend

#653 hotfix: issue with detailed employee endpoint fixed
  src/api-gateway/src/employee/employee.controller.ts
Labels: backend

#654 Refactor/invoices
  src/api-gateway/src/invoices/dto/create-invoice.dto.ts
  src/api-gateway/src/invoices/dto/update-invoice.dto.ts
  src/api-gateway/src/invoices/entities/invoice.entity.ts
  src/api-gateway/src/invoices/invoice.service.ts
Labels: backend

#655 hotfix: issue with employee detailed endpoint fixed
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/employee.service.ts
Labels: backend

#656 hotfix: another issue with employee fixed
  src/api-gateway/src/employee/employee.controller.ts
Labels: backend

#657 Addition of subordinates on view and edit
  src/frontend/src/components/home/employees/management/AddEmployee.vue
  src/frontend/src/components/home/employees/management/EditEmployee.vue
  src/frontend/src/components/home/employees/management/EmployeeDetails.vue
Labels: bug, Enhancement, feature, frontend

#658 Refactor/frontend pt4
  src/frontend/package.json
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/components/home/clients/feedback/CustomerFeedback.vue
  src/frontend/src/components/home/clients/management/AddClient.vue
  src/frontend/src/components/home/clients/management/ClientDesk.vue
  src/frontend/src/components/home/clients/management/DeleteClient.vue
  src/frontend/src/components/home/clients/management/EditClient.vue
  src/frontend/src/components/home/inventory/management/AddInventory.vue
  src/frontend/src/components/home/inventory/management/InventoryDetails.vue
  src/frontend/src/components/home/inventory/management/StockTakeManagement.vue
  src/frontend/src/components/home/inventory/reports/InventoryReports.vue
  src/frontend/src/components/home/invoices/DeleteInvoice.vue
  src/frontend/src/components/home/invoices/ViewInvoices.vue
  src/frontend/src/components/home/jobs/management/AddComments.vue
  src/frontend/src/components/home/jobs/management/ChangeClientDialog.vue
  src/frontend/src/components/home/jobs/management/CheckOffItems.vue
  src/frontend/src/components/home/jobs/management/GenerateInvoice.vue
  src/frontend/src/components/home/jobs/management/GetJobImages.vue
  src/frontend/src/components/home/jobs/management/JobHistory.vue
  src/frontend/src/components/home/jobs/management/JobStatus.vue
  src/frontend/src/components/home/jobs/management/JobTags.vue
  src/frontend/src/components/home/jobs/management/LogJobInventory.vue
  src/frontend/src/components/home/jobs/management/ManagerJobCard.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
  src/frontend/src/components/home/notifications/appointments/VideoConferencing.vue
  src/frontend/src/components/home/notifications/management/NotificationsPage.vue
  src/frontend/src/components/home/settings/company/CreatePriority.vue
  src/frontend/src/components/home/settings/company/DeletePriority.vue
  src/frontend/src/components/home/settings/company/DeleteRole.vue
  src/frontend/src/components/home/settings/company/DeleteStatus.vue
  src/frontend/src/components/home/settings/company/EditPriority.vue
  src/frontend/src/components/home/settings/company/EditStatus.vue
  src/frontend/src/components/home/settings/company/EditStructure.vue
  src/frontend/src/components/home/settings/company/ManageCompanies.vue
  src/frontend/src/components/home/teams/management/CreateTeam.vue
  src/frontend/src/components/home/teams/management/ViewTeam.vue
  src/frontend/src/main.ts
  src/frontend/src/router/index.ts
  src/frontend/src/shims-vue.d.ts
  src/frontend/src/views/notfications/VideoMeetings.vue
Labels: Enhancement, frontend

#661 Update on PWA and kanban for invoice
  package.json
  src/frontend/package.json
  src/frontend/public/apple-touch-icon.png
  src/frontend/public/favicon-16x16.png
  src/frontend/public/favicon-32x32.png
  src/frontend/public/favicon.ico
  src/frontend/public/pwa-192x192.png
  src/frontend/public/pwa-512x512.png
  src/frontend/public/pwa-maskable-192x192.png
  src/frontend/public/pwa-maskable-512x512.png
  src/frontend/src/components/home/invoices/InvKanbanV1/InvoiceKanban.vue
  src/frontend/src/components/home/invoices/types.ts
  src/frontend/src/router/index.ts
  src/frontend/vite.config.ts
Labels: Enhancement, feature, frontend, integration

#666 Refactor/company settings paymentgateway
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/company/dto/update-company.dto.ts
  src/api-gateway/src/company/entities/company.entity.ts
  src/frontend/src/components/home/clients/client_portal/PaymentPortal.vue
  src/frontend/src/components/home/settings/company/SetupPaymentGateway.vue
Labels: backend

#667 Fixed backend not starting
  src/api-gateway/package.json
  src/api-gateway/src/async-api.ts
  src/api-gateway/src/chat/chat.gateway.ts
  src/api-gateway/src/main.ts
Labels: WontFix

#668 hotfix: issue with stocktake fixed
  src/api-gateway/src/inventory/inventory.service.ts
  src/api-gateway/src/stockmovements/entities/stockmovements.entity.ts
  src/api-gateway/src/stockmovements/stockmovements.service.ts
  src/api-gateway/src/stocktake/dto/create-stocktake.dto.ts
  src/api-gateway/src/stocktake/entities/stocktake.entity.ts
  src/api-gateway/src/stocktake/stocktake.controller.ts
  src/api-gateway/src/stocktake/stocktake.service.ts
Labels: backend

#669 Feature/invntory center integration
  src/api-gateway/src/inventory/dto/update-inventory.dto.ts
  src/api-gateway/src/inventory/inventory.controller.ts
  src/api-gateway/src/inventory/inventory.service.ts
  src/api-gateway/src/stockmovements/stockmovements.controller.ts
  src/api-gateway/src/stockmovements/stockmovements.repository.ts
  src/api-gateway/src/stockmovements/stockmovements.service.ts
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/components/home/inventory/management/EditInventory.vue
  src/frontend/src/components/home/inventory/reports/InventoryReports.vue
  src/frontend/src/components/home/teams/management/CreateTeam.vue
Labels: frontend, backend

#676 Feature/video confrence
  src/api-gateway/package.json
  src/api-gateway/src/app.module.ts
  src/api-gateway/src/main.ts
  src/api-gateway/src/video-call/dto/create-video-call.dto.ts
  src/api-gateway/src/video-call/dto/update-video-call.dto.ts
  src/api-gateway/src/video-call/entities/video-call.entity.ts
  src/api-gateway/src/video-call/video-call.controller.ts.ts
  src/api-gateway/src/video-call/video-call.module.ts
  src/api-gateway/src/video-call/video-call.repository.ts
  src/api-gateway/src/video-call/video-call.service.ts
  src/api-gateway/src/video-call/webrtc.gateway.ts
  src/frontend/package.json
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/components/home/invoices/ViewInvoices.vue
  src/frontend/src/components/home/notifications/appointments/AppointmentsPage.vue
  src/frontend/src/components/home/notifications/appointments/VideoConferencing.vue
  src/frontend/tsconfig.app.json
Labels: backend

#681 Feature/fleet
  src/api-gateway/package.json
  src/api-gateway/src/admin/admin.service.ts
  src/api-gateway/src/app.module.ts
  src/api-gateway/src/client/client.repository.ts
  src/api-gateway/src/client/client.service.ts
  src/api-gateway/src/company/company.repository.ts
  src/api-gateway/src/company/company.service.ts
  src/api-gateway/src/email/email.module.ts
  src/api-gateway/src/email/email.service.ts
  src/api-gateway/src/email/templates/client-portal.hbs
  src/api-gateway/src/employee/employee.module.ts
  src/api-gateway/src/fleet/data/vehicle-data.csv
  src/api-gateway/src/fleet/dto/add-vehicle-information.dto.ts
  src/api-gateway/src/fleet/dto/create-vehicle.dto.ts
  src/api-gateway/src/fleet/dto/fleet-response.dto.ts
  src/api-gateway/src/fleet/dto/update-vehicle.dto.ts
  src/api-gateway/src/fleet/entities/vehicle.entity.ts
  src/api-gateway/src/fleet/fleet.controller.ts
  src/api-gateway/src/fleet/fleet.module.ts
  src/api-gateway/src/fleet/fleet.repository.ts
  src/api-gateway/src/fleet/fleet.service.ts
  src/api-gateway/src/fleet/models/vehicle-info.model.ts
  src/api-gateway/src/fleet/vehicle-information.service.ts
  src/api-gateway/src/fleet/vehicle.controller.ts
  src/api-gateway/src/fleet/vehicle.module.ts
  src/api-gateway/src/inventory/inventory.module.ts
  src/api-gateway/src/job/job.module.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/role/role.module.ts
  src/api-gateway/src/stockmovements/stockmovements.module.ts
  src/api-gateway/src/stocktake/stocktake.module.ts
  src/api-gateway/src/team/team.module.ts
  src/api-gateway/src/time-tracker/time-tracker.module.ts
  src/api-gateway/src/users/dto/request-to-join.dto.ts
  src/frontend/index.html
  src/frontend/package.json
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/main.ts
  src/frontend/src/router/index.ts
  src/frontend/src/views/home/map/GoogleMapsView.vue
  src/frontend/src/views/home/map/Map.vue
  src/frontend/src/views/home/map/models/vehicles.ts
  src/frontend/src/views/home/map/types.ts
  src/frontend/src/vue3-geolocation.d.ts
Labels: Enhancement, feature, backend

#684 Refactro/invoices
  src/api-gateway/src/invoices/dto/create-invoice.dto.ts
  src/api-gateway/src/invoices/dto/update-invoice.dto.ts
  src/api-gateway/src/invoices/entities/invoice.entity.ts
  src/api-gateway/src/invoices/invoice.controller.ts
  src/api-gateway/src/invoices/invoice.service.ts
  uploads/9f55e355-1f55-4bf0-af66-58dc1ca902a3-20231217_144916.jpg
Labels: backend

#687 Refactor/smoll fixes
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/components/home/clients/feedback/CustomerFeedback.vue
  src/frontend/src/components/home/inventory/reports/InventoryReports.vue
  src/frontend/src/components/home/invoices/InvoiceDashboard.vue
  src/frontend/src/components/home/jobs/management/JobAssignmentTable.vue
  src/frontend/src/components/home/notifications/appointments/AppointmentsPage.vue
  src/frontend/src/components/home/notifications/appointments/VideoConferencing.vue
  src/frontend/src/components/home/settings/company/EditRoles.vue
Labels: frontend, backend

#693 feature/jobAssignmentView4
  package.json
  src/api-gateway/src/inventory-used/dto/update-inventory-used.dto.ts
  src/api-gateway/src/inventory-used/entities/inventory-used.entity.ts
  src/api-gateway/src/inventory-used/inventory-used.repository.ts
  src/api-gateway/src/inventory-used/inventory-used.service.ts
  src/api-gateway/src/inventory/inventory.controller.ts
  src/api-gateway/src/inventory/inventory.service.ts
  src/api-gateway/src/invoices/entities/invoice.entity.ts
  src/api-gateway/src/invoices/invoice.controller.ts
  src/api-gateway/src/invoices/invoice.repository.ts
  src/api-gateway/src/invoices/invoice.service.ts
  src/api-gateway/src/job/entities/job.entity.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/time-tracker/time-tracker.controller.ts
  src/api-gateway/src/time-tracker/time-tracker.repository.ts
  src/frontend/package.json
  src/frontend/src/assets/theme.css
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/components/home/chat/ChatHeader.vue
  src/frontend/src/components/home/chat/ChatInput.vue
  src/frontend/src/components/home/chat/ChatMessageList.vue
  src/frontend/src/components/home/chat/ChatSideBar.vue
  src/frontend/src/components/home/chat/ChatUI.vue
  src/frontend/src/components/home/inventory/management/StockTakeManagement.vue
  src/frontend/src/components/home/invoices/InvKanbanV1/InvoiceKanban.vue
  src/frontend/src/components/home/jobs/management/CheckOffItems.vue
  src/frontend/src/components/home/jobs/management/GenerateInvoice.vue
  src/frontend/src/components/home/jobs/management/JobAssignmentTable.vue
  src/frontend/src/components/home/jobs/management/JobTags.vue
  src/frontend/src/components/home/jobs/management/LogJobInventory.vue
  src/frontend/src/components/home/jobs/management/ManagerJobCard.vue
  src/frontend/src/components/home/jobs/management/SelectMembers.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
  src/frontend/src/components/home/teams/management/UpdateTeam.vue
  src/frontend/src/main.ts
  src/frontend/src/types/colorthief.d.ts
  src/frontend/src/views/home/map/Map.vue
  src/frontend/tsconfig.json
Labels: bug, frontend, integration

#678 Feature/stats
  src/api-gateway/src/app.module.ts
  src/api-gateway/src/client/client.repository.ts
  src/api-gateway/src/client/client.service.ts
  src/api-gateway/src/invoices/dto/update-invoice.dto.ts
  src/api-gateway/src/invoices/entities/invoice.entity.ts
  src/api-gateway/src/invoices/invoice.repository.ts
  src/api-gateway/src/invoices/invoice.service.ts
  src/api-gateway/src/job/job.repository.ts
  src/api-gateway/src/job/job.service.ts
  src/api-gateway/src/stats/dto/stats-response.dto.ts
  src/api-gateway/src/stats/stats.controller.ts
  src/api-gateway/src/stats/stats.module.ts
  src/api-gateway/src/stats/stats.service.ts
  src/api-gateway/src/stockmovements/stockmovements.repository.ts
  src/api-gateway/src/stockmovements/stockmovements.service.ts
  src/frontend/src/components/home/statistics/ClientBreakdown.vue
  src/frontend/src/components/home/statistics/EmployeeBreakdown.vue
  src/frontend/src/components/home/statistics/InventoryBreakdown.vue
  src/frontend/src/components/home/statistics/InvoiceBreakdown.vue
  src/frontend/src/components/home/statistics/JobBreakdown.vue
  src/frontend/src/components/home/statistics/StatisticsDashboard.vue
  src/frontend/src/components/home/statistics/TeamBreakdown.vue
  src/frontend/src/plugins/vuetify.ts
Labels: feature, frontend, backend

#680 Refactor/frontend pt6
  src/api-gateway/src/invoices/dto/create-invoice.dto.ts
  src/frontend/src/assets/theme.css
  src/frontend/src/components/home/chat/ChatHeader.vue
  src/frontend/src/components/home/clients/client_portal/ClientPortal.vue
  src/frontend/src/components/home/inventory/management/EditInventory.vue
  src/frontend/src/components/home/inventory/management/InventoryDashboard.vue
  src/frontend/src/components/home/inventory/reports/InventoryReports.vue
  src/frontend/src/components/home/invoices/EditInvoice.vue
  src/frontend/src/components/home/invoices/InvoiceCenter.vue
  src/frontend/src/components/home/invoices/InvoiceDashboard.vue
  src/frontend/src/components/home/invoices/ViewInvoices.vue
  src/frontend/src/components/home/jobs/management/GenerateInvoice.vue
  src/frontend/src/components/home/jobs/management/JobHistory.vue
  src/frontend/src/components/home/jobs/management/JobStatus.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
  src/frontend/src/components/home/notifications/appointments/AppointmentsPage.vue
  src/frontend/src/components/home/notifications/appointments/VideoConferencing.vue
  src/frontend/src/components/home/settings/SettingsMenu.vue
  src/frontend/src/components/home/settings/company/EditRoles.vue
  src/frontend/src/components/home/settings/company/EditStructure.vue
  src/frontend/src/components/home/teams/management/ViewTeam.vue
  src/frontend/src/components/signup/SplashScreen.vue
  src/frontend/src/index.css
  src/frontend/src/router/index.ts
  src/frontend/src/store/user-store.js
  src/frontend/src/styles.css
  src/frontend/src/views/home/chat/ChatHome.vue
  src/frontend/src/views/home/clients/ClientPortalView.vue
Labels: Enhancement, feature, frontend

#685 Bugfix/team
  src/api-gateway/src/team/team.controller.ts
  src/api-gateway/src/team/team.repository.ts
  src/api-gateway/src/team/team.service.ts
  src/frontend/src/components/home/teams/management/TeamsDashboard.vue
  src/frontend/src/components/home/teams/management/UpdateTeam.vue
  src/frontend/src/components/home/teams/management/ViewTeam.vue
Labels: backend

#686 Refactor/client portal
  src/frontend/src/components/home/clients/client_portal/PaymentPortal.vue
  src/frontend/src/components/home/clients/client_portal/ReviewJob.vue
  src/frontend/src/components/home/clients/client_portal/ViewJobs.vue
Labels: backend

#698 feature/jobAssignmentView4
  src/frontend/src/assets/theme.css
  src/frontend/src/components/home/chat/ChatSideBar.vue
  src/frontend/src/components/home/inventory/management/StockTakeManagement.vue
  src/frontend/src/components/home/jobs/management/AddComments.vue
  src/frontend/src/components/home/jobs/management/CheckOffItems.vue
  src/frontend/src/components/home/jobs/management/GetJobImages.vue
  src/frontend/src/components/home/jobs/management/JobAssignmentTable.vue
  src/frontend/src/components/home/jobs/management/JobHistory.vue
  src/frontend/src/components/home/jobs/management/JobTags.vue
  src/frontend/src/views/home/map/Map.vue
Labels: bug, frontend, integration

#699 system-integration-V5
  src/api-gateway/src/invoices/invoice.repository.ts
  src/frontend/src/components/home/clients/client_portal/PaymentPortal.vue
  src/frontend/src/components/home/employees/management/DeleteEmployee.vue
  src/frontend/src/components/home/employees/management/EditEmployee.vue
  src/frontend/src/components/home/employees/management/EmployeeDetails.vue
  src/frontend/src/components/home/employees/management/ManageEmployees.vue
  src/frontend/src/components/home/invoices/InvKanbanV1/InvoiceKanban.vue
  src/frontend/src/components/home/invoices/ViewInvoices.vue
  src/frontend/src/components/home/jobs/KanbanV2/KanbanV2.vue
  src/frontend/src/components/home/notifications/management/NotificationsPage.vue
  src/frontend/vite.config.ts
Labels: Enhancement, feature, frontend, integration

#702 feature/jobAssignmentView4
  cypress.config.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/component.ts
  src/frontend/cypress.config.ts
  src/frontend/cypress/e2e/example.cy.ts
  src/frontend/cypress/support/component.ts
  src/frontend/src/components/home/jobs/management/GenerateInvoice.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
Labels: bug, feature, frontend

#705 feature/jobAssignmentView4
  package.json
  src/api-gateway/src/invoices/entities/invoice.entity.ts
  src/frontend/src/components/home/clients/__tests__/AddClient.cy.ts
  src/frontend/src/components/home/clients/__tests__/ClientPortal.cy.ts
  src/frontend/src/components/home/employees/__tests__/AddEmp.cy.ts
  src/frontend/src/components/home/inventory/management/StockTakeManagement.vue
  src/frontend/src/components/home/jobs/__tests__/JobChecklist.cy.ts
  src/frontend/src/components/home/jobs/management/GenerateInvoice.vue
  src/frontend/src/components/home/notifications/__tests__/MessageBoard.cy.ts
Labels: bug, frontend

#703 Feature/no access page
  src/frontend/src/components/misc/NoAccess.vue
  src/frontend/src/components/signup/SplashScreen.vue
  src/frontend/src/router/index.ts
Labels: Enhancement, feature, frontend

#706 Refactor/system refactor
  src/api-gateway/src/company/company.controller.ts
  src/api-gateway/src/email/email.service.ts
  src/api-gateway/src/email/templates/client-portal-invoice.hbs
  src/api-gateway/src/employee/dto/internal-update-employee.dto.ts
  src/api-gateway/src/employee/employee.controller.ts
  src/api-gateway/src/employee/employee.service.ts
  src/api-gateway/src/invoices/dto/update-invoice.dto.ts
  src/api-gateway/src/invoices/entities/invoice.entity.ts
  src/api-gateway/src/invoices/invoice.controller.ts
  src/api-gateway/src/invoices/invoice.repository.ts
  src/api-gateway/src/invoices/invoice.service.ts
  src/api-gateway/src/job/job.controller.ts
  src/api-gateway/src/role/role.controller.ts
  src/api-gateway/src/role/role.service.ts
  src/frontend/src/components/home/clients/client_portal/ClientPortal.vue
  src/frontend/src/components/home/clients/client_portal/PaymentPortal.vue
  src/frontend/src/components/home/invoices/EditInvoice.vue
  src/frontend/src/components/home/invoices/InvKanbanV1/InvoiceKanban.vue
  src/frontend/src/components/home/invoices/InvoiceDashboard.vue
  src/frontend/src/components/home/invoices/SendInvoice.vue
  src/frontend/src/components/home/invoices/ViewInvoices.vue
  src/frontend/src/components/home/jobs/management/ViewJob.vue
  src/frontend/src/components/home/settings/company/HourlyRate.vue
Labels: frontend, backend

#704 Refactor frontend pt7
  src/api-gateway/src/stats/stats.service.ts
  src/frontend/src/components/home/NavigationBar.vue
  src/frontend/src/components/home/chat/ChatInput.vue
  src/frontend/src/components/home/chat/ChatSideBar.vue
  src/frontend/src/components/home/clients/client_portal/ReviewJob.vue
  src/frontend/src/components/home/clients/feedback/CustomerFeedback.vue
  src/frontend/src/components/home/clients/management/DeleteClient.vue
  src/frontend/src/components/home/clients/management/EditClient.vue
  src/frontend/src/components/home/dashboard/home/Calendar.vue
  src/frontend/src/components/home/employees/management/AddEmployee.vue
  src/frontend/src/components/home/inventory/management/DeleteInventory.vue
  src/frontend/src/components/home/inventory/management/InventoryDashboard.vue
  src/frontend/src/components/home/inventory/management/StockTakeManagement.vue
  src/frontend/src/components/home/inventory/reports/InventoryReports.vue
  src/frontend/src/components/home/invoices/DeleteInvoice.vue
  src/frontend/src/components/home/jobs/KanbanV2/Archive.vue
  src/frontend/src/components/home/jobs/management/ChangeClientDialog.vue
  src/frontend/src/components/home/jobs/management/CheckOffItems.vue
  src/frontend/src/components/home/jobs/management/GetJobImages.vue
  src/frontend/src/components/home/jobs/management/JobAssignmentTable.vue
  src/frontend/src/components/home/jobs/management/JobStatus.vue
  src/frontend/src/components/home/jobs/management/JobTags.vue
  src/frontend/src/components/home/jobs/management/JobTimeTracker.vue
  src/frontend/src/components/home/jobs/management/LogJobInventory.vue
  src/frontend/src/components/home/jobs/task/TaskCenter.vue
  src/frontend/src/components/home/notifications/appointments/AppointmentsPage.vue
  src/frontend/src/components/home/settings/company/CompanyMain.vue
  src/frontend/src/components/home/settings/company/CompanyRequest.vue
  src/frontend/src/components/home/settings/company/DeletePriority.vue
  src/frontend/src/components/home/settings/company/DeleteStatus.vue
  src/frontend/src/components/home/settings/company/DeleteTags.vue
  src/frontend/src/components/home/settings/company/EditCompany.vue
  src/frontend/src/components/home/settings/company/EditStatus.vue
  src/frontend/src/components/home/settings/company/EditStructure.vue
  src/frontend/src/components/home/settings/user/CreateInvite.vue
  src/frontend/src/components/home/settings/user/InvitePage.vue
  src/frontend/src/components/home/statistics/ClientBreakdown.vue
  src/frontend/src/components/home/statistics/EmployeeBreakdown.vue
  src/frontend/src/components/home/statistics/InventoryBreakdown.vue
  src/frontend/src/components/home/statistics/InvoiceBreakdown.vue
  src/frontend/src/components/home/statistics/JobBreakdown.vue
  src/frontend/src/components/home/statistics/TeamBreakdown.vue
  src/frontend/src/components/home/teams/management/CreateTeam.vue
  src/frontend/src/components/home/teams/management/DeleteTeam.vue
  src/frontend/src/components/home/teams/management/TeamsDashboard.vue
  src/frontend/src/components/home/teams/management/UpdateTeam.vue
  src/frontend/src/components/signup/RegisterCompanyModal.vue
  src/frontend/src/plugins/vuetify.ts
  src/frontend/src/types/colorthief.d.ts
  src/frontend/src/views/home/map/Map.vue
Labels: Enhancement, feature, frontend

#711 Feature/dem4 slides
  revealJS/index.html
Labels: Documentation

#713 hotfix/fleet
  src/api-gateway/src/fleet/dto/create-vehicle.dto.ts
  src/api-gateway/src/fleet/entities/vehicle.entity.ts
  src/frontend/package.json
  src/frontend/public/car.png
  src/frontend/src/assets/images/markers/BuildingMarker.png
  src/frontend/src/assets/images/markers/CarMarker.png
  src/frontend/src/assets/images/markers/PersonMarker.png
  src/frontend/src/views/home/map/Map.vue
Labels: bug, frontend, integration
